import { Model, DataTypes } from 'sequelize';
import { sequelize } from "../../database/database.js"; // Asegúrate de que la ruta sea correcta

// Declaramos la clase que hereda de Model
const FundamentalModel = sequelize.define('fundamentals', {
    symbol: { type: DataTypes.STRING(255), allowNull: false, primaryKey: true },
    date: { type: DataTypes.DATEONLY, allowNull: false, primaryKey: true },
    isYearly: { type: DataTypes.BOOLEAN, defaultValue: false, primaryKey: true },
    periodType: { type: DataTypes.STRING(10), allowNull: false },

    // 📈 Estado de Resultados (Income Statement) & Ratios por Acción
    totalRevenue: DataTypes.DOUBLE,
    operatingRevenue: DataTypes.DOUBLE,
    costOfRevenue: DataTypes.DOUBLE,
    reconciledCostOfRevenue: DataTypes.DOUBLE,
    grossProfit: DataTypes.DOUBLE,
    researchAndDevelopment: DataTypes.DOUBLE,
    sellingGeneralAndAdministration: DataTypes.DOUBLE,
    operatingExpense: DataTypes.DOUBLE,
    operatingIncome: DataTypes.DOUBLE,
    totalOperatingIncomeAsReported: DataTypes.DOUBLE,
    totalExpenses: DataTypes.DOUBLE,
    EBIT: DataTypes.DOUBLE,
    EBITDA: DataTypes.DOUBLE,
    normalizedEBITDA: DataTypes.DOUBLE,
    pretaxIncome: DataTypes.DOUBLE,
    taxProvision: DataTypes.DOUBLE,
    taxRateForCalcs: DataTypes.FLOAT,
    netIncomeFromContinuingOperations: DataTypes.DOUBLE,
    netIncomeContinuousOperations: DataTypes.DOUBLE,
    netIncomeIncludingNoncontrollingInterests: DataTypes.DOUBLE,
    netIncomeFromContinuingAndDiscontinuedOperation: DataTypes.DOUBLE,
    netIncomeFromContinuingOperationNetMinorityInterest: DataTypes.DOUBLE,
    netIncomeCommonStockholders: DataTypes.DOUBLE,
    dilutedNIAvailtoComStockholders: DataTypes.DOUBLE,
    netIncome: DataTypes.DOUBLE,
    normalizedIncome: DataTypes.DOUBLE,
    otherNonOperatingIncomeExpenses: DataTypes.DOUBLE,
    otherIncomeExpense: DataTypes.DOUBLE,
    basicEPS: DataTypes.DECIMAL(10, 4),
    dilutedEPS: DataTypes.DECIMAL(10, 4),
    basicAverageShares: DataTypes.DOUBLE,
    dilutedAverageShares: DataTypes.DOUBLE,
    ordinarySharesNumber: DataTypes.DOUBLE,
    shareIssued: DataTypes.DOUBLE,

    // 🏛️ Balance General (Balance Sheet)
    // Activos (Assets)
    cashAndCashEquivalents: DataTypes.DOUBLE,
    cashEquivalents: DataTypes.DOUBLE,
    cashFinancial: DataTypes.DOUBLE,
    otherShortTermInvestments: DataTypes.DOUBLE,
    cashCashEquivalentsAndShortTermInvestments: DataTypes.DOUBLE,
    accountsReceivable: DataTypes.DOUBLE,
    receivables: DataTypes.DOUBLE,
    otherReceivables: DataTypes.DOUBLE,
    inventory: DataTypes.DOUBLE,
    otherCurrentAssets: DataTypes.DOUBLE,
    currentAssets: DataTypes.DOUBLE,
    machineryFurnitureEquipment: DataTypes.DOUBLE,
    landAndImprovements: DataTypes.DOUBLE,
    grossPPE: DataTypes.DOUBLE,
    accumulatedDepreciation: DataTypes.DOUBLE,
    netPPE: DataTypes.DOUBLE,
    nonCurrentDeferredTaxesAssets: DataTypes.DOUBLE,
    nonCurrentDeferredAssets: DataTypes.DOUBLE,
    investmentsAndAdvances: DataTypes.DOUBLE,
    investmentinFinancialAssets: DataTypes.DOUBLE,
    availableForSaleSecurities: DataTypes.DOUBLE,
    otherNonCurrentAssets: DataTypes.DOUBLE,
    totalNonCurrentAssets: DataTypes.DOUBLE,
    totalAssets: DataTypes.DOUBLE,
    // Pasivos (Liabilities)
    accountsPayable: DataTypes.DOUBLE,
    payables: DataTypes.DOUBLE,
    currentAccruedExpenses: DataTypes.DOUBLE,
    payablesAndAccruedExpenses: DataTypes.DOUBLE,
    incomeTaxPayable: DataTypes.DOUBLE,
    totalTaxPayable: DataTypes.DOUBLE,
    currentDeferredRevenue: DataTypes.DOUBLE,
    currentDeferredLiabilities: DataTypes.DOUBLE,
    commercialPaper: DataTypes.DOUBLE,
    otherCurrentBorrowings: DataTypes.DOUBLE,
    currentDebt: DataTypes.DOUBLE,
    currentDebtAndCapitalLeaseObligation: DataTypes.DOUBLE,
    otherCurrentLiabilities: DataTypes.DOUBLE,
    currentLiabilities: DataTypes.DOUBLE,
    longTermDebt: DataTypes.DOUBLE,
    longTermDebtAndCapitalLeaseObligation: DataTypes.DOUBLE,
    leases: DataTypes.DOUBLE,
    otherNonCurrentLiabilities: DataTypes.DOUBLE,
    totalNonCurrentLiabilitiesNetMinorityInterest: DataTypes.DOUBLE,
    totalLiabilitiesNetMinorityInterest: DataTypes.DOUBLE,
    // Patrimonio (Equity)
    capitalStock: DataTypes.DOUBLE,
    commonStock: DataTypes.DOUBLE,
    retainedEarnings: DataTypes.DOUBLE,
    gainsLossesNotAffectingRetainedEarnings: DataTypes.DOUBLE,
    otherEquityAdjustments: DataTypes.DOUBLE,
    commonStockEquity: DataTypes.DOUBLE,
    stockholdersEquity: DataTypes.DOUBLE,
    totalEquityGrossMinorityInterest: DataTypes.DOUBLE,
    // Métricas de Capital Calculadas
    workingCapital: DataTypes.DOUBLE,
    investedCapital: DataTypes.DOUBLE,
    tangibleBookValue: DataTypes.DOUBLE,
    netTangibleAssets: DataTypes.DOUBLE,
    totalCapitalization: DataTypes.DOUBLE,
    netDebt: DataTypes.DOUBLE,

    // 💸 Estado de Flujo de Caja (Cash Flow)
    operatingCashFlow: DataTypes.DOUBLE,
    cashFlowFromContinuingOperatingActivities: DataTypes.DOUBLE,
    depreciationAndAmortization: DataTypes.DOUBLE,
    depreciationAmortizationDepletion: DataTypes.DOUBLE,
    reconciledDepreciation: DataTypes.DOUBLE,
    stockBasedCompensation: DataTypes.DOUBLE,
    otherNonCashItems: DataTypes.DOUBLE,
    // Cambios en Capital de Trabajo
    changeInWorkingCapital: DataTypes.DOUBLE,
    changeInAccountPayable: DataTypes.DOUBLE,
    changeInPayable: DataTypes.DOUBLE,
    changeInPayablesAndAccruedExpense: DataTypes.DOUBLE,
    changeInReceivables: DataTypes.DOUBLE,
    changesInAccountReceivables: DataTypes.DOUBLE,
    changeInInventory: DataTypes.DOUBLE,
    changeInOtherCurrentAssets: DataTypes.DOUBLE,
    changeInOtherCurrentLiabilities: DataTypes.DOUBLE,
    // Actividades de Inversión
    capitalExpenditure: DataTypes.DOUBLE,
    purchaseOfPPE: DataTypes.DOUBLE,
    netPPEPurchaseAndSale: DataTypes.DOUBLE,
    purchaseOfInvestment: DataTypes.DOUBLE,
    saleOfInvestment: DataTypes.DOUBLE,
    netInvestmentPurchaseAndSale: DataTypes.DOUBLE,
    netOtherInvestingChanges: DataTypes.DOUBLE,
    investingCashFlow: DataTypes.DOUBLE,
    cashFlowFromContinuingInvestingActivities: DataTypes.DOUBLE,
    // Actividades de Financiación
    issuanceOfDebt: DataTypes.DOUBLE,
    longTermDebtIssuance: DataTypes.DOUBLE,
    repaymentOfDebt: DataTypes.DOUBLE,
    longTermDebtPayments: DataTypes.DOUBLE,
    netIssuancePaymentsOfDebt: DataTypes.DOUBLE,
    netLongTermDebtIssuance: DataTypes.DOUBLE,
    netShortTermDebtIssuance: DataTypes.DOUBLE,
    repurchaseOfCapitalStock: DataTypes.DOUBLE,
    commonStockPayments: DataTypes.DOUBLE,
    netCommonStockIssuance: DataTypes.DOUBLE,
    cashDividendsPaid: DataTypes.DOUBLE,
    commonStockDividendPaid: DataTypes.DOUBLE,
    netOtherFinancingCharges: DataTypes.DOUBLE,
    financingCashFlow: DataTypes.DOUBLE,
    cashFlowFromContinuingFinancingActivities: DataTypes.DOUBLE,
    // Totales de Caja
    beginningCashPosition: DataTypes.DOUBLE,
    endCashPosition: DataTypes.DOUBLE,
    changesInCash: DataTypes.DOUBLE,
    freeCashFlow: DataTypes.DOUBLE,
    incomeTaxPaidSupplementalData: DataTypes.DOUBLE
}, {
    timestamps: true,
});

FundamentalModel.asociate = function () {
    const enterprises = sequelize.model('enterprises');
    this.belongsTo(enterprises, { foreignKey: 'symbol' });
}

export default FundamentalModel;